export const DISPLAY_RESTAURANTS = "DISPLAY_RESTAURANTS";
export const DISPLAY_SINGLE_RESTAURANT = "DISPLAY_SINGLE_RESTAURANT";
export const CREATE_RESTAURANT = "CREATE_RESTAURANT";
export const GET_NEW_RESTAURANT = "GET_NEW_RESTAURANT";
export const CREATE_REVIEW = "CREATE_REVIEW";